const trainingData = [
  "Hello, how are you doing today",
  "Good morning, I hope you have a great day",
  "Good afternoon, it is nice to see you again",
  "Good evening, how has your day been so far",
  "Hi there, what are you working on",
  "Hey, long time no see",
  "Greetings from the development team",
  "Welcome aboard, we are glad to have you",
  "Nice to meet you, let's start coding",
  "Pleased to meet you, I am Shivam",

  // Coding related
  "JavaScript is a dynamically typed language",
  "Node.js runs JavaScript on the server",
  "Variables can be declared with let, const, or var",
  "Functions help reuse code and keep it organized",
  "Objects are collections of key value pairs",
  "Arrays store ordered lists of items",
  "npm is the default package manager for Node.js",
  "pnpm is a faster alternative to npm",
  "A tokenizer converts text into tokens",
  "APIs allow communication between different software components",
  "JSON is a lightweight data format",
  "Loops help repeat actions efficiently",
  "Conditionals help make decisions in code",
  "Frontend and backend work together in web applications",
  "React is a popular JavaScript library for building UIs",
  "Express is a lightweight Node.js framework",
  "Databases store and retrieve structured data",
  "SQL is used for querying relational databases",
  "MongoDB is a NoSQL database",

  "How have you been",
  "What are your weekend plans",
  "Happy birthday to you",
  "Happy new year, may it be full of joy",
  "Congratulations on your achievement",
  "Best wishes for your journey ahead",
  "See you later",
  "Talk to you soon",
  "It was nice talking to you",
  "Take care and stay safe",
  "I will get back to you shortly",
  "Thank you for your help",
  "Thanks a lot for the quick response",
  "I appreciate your support",
  "Good luck with your project",

  // Mixed technical terms & phrases
  "Machine learning models learn patterns from data",
  "Artificial intelligence is changing industries",
  "Git is a version control system",
  "GitHub hosts repositories online",
  "Commit messages should be clear and descriptive",
  "Pull requests allow collaboration",
  "Merging code requires conflict resolution",
  "Testing ensures software quality",
  "Unit tests check small pieces of functionality",
  "Integration tests verify how components work together",
  "Continuous integration automates building and testing",
  "Docker allows containerization of applications",
  "Kubernetes orchestrates containerized services",
  "Cloud computing provides on demand resources",
  "AWS, Azure, and GCP are major cloud providers",

  // Random general words to expand vocab
  "Sunshine makes the day brighter",
  "The rain was gentle and refreshing",
  "Mountains are beautiful and majestic",
  "Rivers flow endlessly toward the ocean",
  "Books open the door to new worlds",
  "Music can lift the spirit and heal the soul",
  "Cooking at home is both fun and healthy",
  "Exercise keeps the body fit and the mind sharp",
  "Travel broadens your perspective",
  "Photography captures precious memories",
  "Art expresses emotions words cannot",
  "Languages connect people from different cultures",
  "Learning something new every day is important",
  "Challenges make you stronger",
  "Persistence leads to success",
  "Failure is a stepping stone to learning",
  "Teamwork makes the dream work",
  "Leadership is about inspiring others",
  "Creativity fuels innovation",
  "Focus determines reality",
];

export default trainingData;
